Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-large-patch16-224-in21k and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/gpfs/users/yutaoc/ai_task/main.py", line 9, in <module>
    from src.training.train import train_epoch, validate
  File "/gpfs/users/yutaoc/ai_task/src/training/train.py", line 42, in <module>
    train_loss, train_acc = train_epoch(model, train_loader, optimizer, scaler, device)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/users/yutaoc/ai_task/src/utils/utils.py", line 19, in train_epoch
    with torch.amp.autocast(dtype=torch.float16):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: autocast.__init__() missing 1 required positional argument: 'device_type'
